# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/*"
  to = "/200.html"
  status = 200

 [build.environment]
  NODE_VERSION = "16.18.1"
  NPM_VERSION = "8.19.2"
